apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-creator
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: topic-creator
          image: bitnami/kafka:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Waiting for Kafka to be ready..."
              until kafka-topics.sh --bootstrap-server kafka:9092 --list > /dev/null 2>&1; do
                echo "Kafka not ready, sleeping..."
                sleep 2
              done
              kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic orders --partitions 1 --replication-factor 1
              kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic inventory --partitions 1 --replication-factor 1
