apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders-app
spec:
  selector:
    app: orders-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
