services:
  order-database:
    build:
      context: .
      dockerfile: docker/databases/orders-data.dockerfile
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - order-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-api:
    build:
      context: .
      dockerfile: docker/orders-command/orders.dockerfile
    container_name: orders-api
    restart: always
    ports:
      - "8000:8000"
    networks:
      - order-network
    depends_on:
      order-database:
        condition: service_healthy

networks:
  order-network:
    driver: bridge

volumes:
  postgres_data:
