apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-app
spec:
  selector:
    app: inventory-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
