apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
        - name: inventory-container
          image: inventory-image:latest
          imagePullPolicy: Never
          env:
            - name: POSTGRES_HOST
              value: "{{ .Values.configuration.postgres.host }}"
            - name: POSTGRES_PORT
              value: "{{ .Values.configuration.postgres.port }}"
            - name: POSTGRES_USER
              value: "{{ .Values.configuration.postgres.user }}"
            - name: POSTGRES_DB
              value: "{{ .Values.configuration.inventory.database_name }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.configuration.postgres.password }}"
            - name: SERVICE_TOPIC_READ
              value: "{{ .Values.configuration.inventory.service_topic_read }}"
            - name: SERVICE_TOPIC_WRITE
              value: "{{ .Values.configuration.inventory.service_topic_write }}"
            - name: KAFKA_HOST
              value: "{{ .Values.configuration.kafka.host }}"
            - name: KAFKA_PORT
              value: "{{ .Values.configuration.kafka.port }}"
          ports:
            - containerPort: 8080